### PR TITLE
Sync with ESCOMP/master to bring component level PIO initialization

### PR DESCRIPTION
**Pull request by uturuncoglu**
### Description of changes
This PR aims to bring component level PIO initialization to support/HAFS

### Specific notes

Contributors other than yourself, if any: None

CDEPS Issues Fixed (include github issue #): None

Testing performed:
- The branch is tested agains the available data model regression tests (DATM+DOCN and DATM+HYCOM) as well as FV3+DOCN(regional) without any problem. It is also tested by running both CDEPS internal tests CESM tests under CIME case control system.

### CODE REVIEW

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good.

**Comment by BinLiu-NOAA** [comment]
@uturuncoglu In order to not break the support/HAFS branch at the model level, please hold this PR so that it goes back into the support/HAFS branch together with the following PRs:
hafs-community/ufs-weather-model#8
hafs-community/CMEPS#1
hafs-community/NEMS#3

**Comment by uturuncoglu** [comment]
@BinLiu-NOAA sure. I am waiting for your approval.

**Review by danrosen25 — COMMENTED** [review]
I'm not familiar with the CDEPS component code or testing. If this has been tested then I approve.

**Comment by uturuncoglu** [comment]
@danrosen25 I run full aux tests in CDEPs side as well ass full CESM test suit and it has lots of configurations combining active components with data components under CDEPS. So, all of them passed without any problem.

**Comment by uturuncoglu** [comment]
I think that we don't need this once we sync with NOAA/EMC fork. So, I am closing this PR.

**Pull request closed without merging**
